name: cleanflutter
description: A new Flutter project with a demo of clean architecture.
version: 0.0.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.0

  path_provider: ^0.4.0

  mock_web_server: ^4.1.1

  mockito: ^4.1.1
  http: ^0.12.0+4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

